version: 1.0.{build}
configuration: Release
platform:
- x86
- x64
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: '*\Release\win32_handmade.exe'
  name: handmadehero
deploy:
- provider: GitHub
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master