version: 0.1.${build}.${platform}
configuration: Release
platform:
- x86
- x64
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: build\hmh${platform}.exe
  name: handmadehero${platform}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.${build}.${platform}"
  assembly_file_version: "${version}.${platform}"
  assembly_informational_version: "${version}.${platform}"
deploy:
- provider: GitHub
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master