version: 1.0.{build}
build:
  parallel: true
  verbosity: normal
artifacts:
- path: build\*.exe
  name: handmade-hero
deploy:
- provider: GitHub
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master