version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
configuration: Release
platform:
- x86
- x64
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: build\${platform}\hmh-${platform}.exe
  name: hmh-${platform}
deploy:
- provider: GitHub
  release: hmh-v$(appveyor_build_version)
  description: Handmade Hero v$(appveyor_build_version)
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
