version: 1.0.{build}
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: x64\Debug\hmh_x64.exe
  name: hmh_x64
deploy:
- provider: GitHub
  auth_token:
    secure: hifcN93/wHdEWIaKpGuJz+M73qcBHaLa6ozBz1fKgporFBvnbZGOiCATSawgKdwX
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master